/** Renderer-owned external Storybook story support. */
export const DOM_INTERFACE_STORY_ROUTES = Object.freeze([
  "dom/interfaces/event-target/listeners/default",
  "dom/interfaces/node/hierarchy/default",
  "dom/interfaces/document/tree/default",
  "dom/interfaces/document-fragment/mutation/default",
  "dom/interfaces/character-data/data/default",
  "dom/interfaces/text/data/default",
  "dom/interfaces/comment/anchors/default",
  "dom/interfaces/node-list/snapshot/default",
  "dom/interfaces/dom-token-list/classes/default",
  "dom/interfaces/element/attributes/default",
  "dom/interfaces/html-element/title/default",
  "dom/interfaces/html-div-element/container/default",
  "dom/interfaces/html-span-element/inline/default",
  "dom/interfaces/html-button-element/activation/default",
  "dom/interfaces/html-input-element/value/default",
  "dom/interfaces/html-image-element/attributes/default",
  "dom/interfaces/html-select-element/selection/default",
  "dom/interfaces/html-option-element/selectedness/default",
  "dom/interfaces/html-progress-element/value/default",
  "dom/interfaces/html-meter-element/value/default",
  "dom/interfaces/html-text-area-element/value/default",
  "dom/interfaces/html-label-element/control/default",
  "dom/interfaces/html-field-set-element/disabled/default",
  "dom/interfaces/html-legend-element/caption/default",
  "dom/interfaces/html-u-list-element/list/default",
  "dom/interfaces/html-li-element/item/default",
  "dom/interfaces/html-heading-element/heading/default",
  "dom/interfaces/html-paragraph-element/text/default",
  "dom/interfaces/html-table-element/table/default",
  "dom/interfaces/html-table-section-element/section/default",
  "dom/interfaces/html-table-row-element/row/default",
  "dom/interfaces/html-table-cell-element/cell/default",
  "dom/interfaces/event/propagation/default",
  "dom/interfaces/custom-event/detail/default",
  "dom/interfaces/toggle-event/states/default",
  "dom/interfaces/ui-event/detail/default",
  "dom/interfaces/focus-event/related-target/default",
  "dom/interfaces/mouse-event/pointer/default",
  "dom/interfaces/pointer-event/samples/default",
  "dom/interfaces/wheel-event/delta/default",
  "dom/interfaces/keyboard-event/key/default",
  "dom/interfaces/input-event/data/default",
  "dom/interfaces/composition-event/data/default",
] as const)

export type DomInterfaceStoryRoute = typeof DOM_INTERFACE_STORY_ROUTES[number]

export const ELEMENT_DOM_STORY_ROUTES = Object.freeze([
  "elements/primitives/div/basic/background",
  "elements/primitives/div/basic/border",
  "elements/primitives/div/basic/padding",
  "elements/primitives/div/basic/z-index",
  "elements/primitives/div/overflow/nested",
  "elements/primitives/div/scroll/vertical",
  "elements/primitives/div/scroll/horizontal",
  "elements/primitives/div/scroll/both",
  "elements/primitives/span/content/left",
  "elements/primitives/span/content/center",
  "elements/primitives/span/content/right",
  "elements/primitives/button/state/default",
  "elements/primitives/button/state/disabled",
  "elements/primitives/button/state/clickable",
  "elements/primitives/input/state/inactive",
  "elements/primitives/input/state/active",
  "elements/primitives/input/state/disabled",
  "elements/primitives/select/state/inactive",
  "elements/primitives/select/state/active",
  "elements/primitives/select/state/disabled",
  "elements/primitives/list/mode/regular",
  "elements/primitives/list/mode/dense",
  "elements/primitives/list/mode/interactive",
  "elements/primitives/list/mode/scroll",
  "elements/primitives/status-bar/content/statistics",
  "elements/style/css/padding/default",
  "elements/style/css/flex/default",
  "elements/style/css/border/rounded",
  "elements/style/css/border/capsule",
  "elements/style/css/color/default",
  "elements/style/css/typography/default",
  "elements/style/theme/tone/cyan",
  "elements/style/theme/tone/green",
  "elements/style/theme/tone/orange",
  "elements/style/theme/tone/red",
  "elements/events/pointer/state/idle",
  "elements/events/pointer/state/hover",
  "elements/events/pointer/state/press",
  "elements/events/pointer/state/release",
  "elements/events/pointer/state/click",
  "elements/events/pointer/state/disabled",
] as const)

export type ElementDomStoryRoute = typeof ELEMENT_DOM_STORY_ROUTES[number]

export const POPOVER_DOM_STORY_ROUTES = Object.freeze([
  "elements/primitives/popover/state/closed",
  "elements/primitives/popover/state/open",
  "elements/primitives/select/state/open",
  "elements/primitives/select/state/header",
  "elements/primitives/select/state/flipped",
] as const)

export type PopoverDomStoryRoute = typeof POPOVER_DOM_STORY_ROUTES[number]

export const IMAGE_DOM_STORY_ROUTES = Object.freeze([
  "elements/primitives/img/fit/cover",
  "elements/primitives/img/fit/contain",
] as const)

export type ImageDomStoryRoute = typeof IMAGE_DOM_STORY_ROUTES[number]
