import {describe, expect, test} from "bun:test"
import {
  AbstractRange,
  Range,
  StaticRange,
  createDocument,
  textOffsetAtPosition,
  textPositionAtOffset,
  setDocumentTextHighlights,
  clearDocumentTextHighlights,
  readDocumentTextHighlights,
  subscribeDocumentTextHighlights,
} from "@zavx0z/dom"

function sample() {
  const document = createDocument()
  const root = document.createElement("article")
  const first = document.createElement("p")
  const code = document.createElement("code")
  const last = document.createElement("p")
  const a = document.createTextNode("alpha ")
  const b = document.createTextNode("beta\nγ")
  const c = document.createTextNode(" omega")
  document.appendChild(root)
  root.append(first, code, last)
  first.appendChild(a)
  code.appendChild(b)
  last.appendChild(c)
  return {document, root, first, code, last, a, b, c}
}

describe("Document Range and Selection", () => {
  test("one selection per Document, one range, stable range identity and direction", () => {
    const {document, a, b} = sample()
    const selection = document.getSelection()
    expect(selection).toBe(document.getSelection())
    expect(selection.rangeCount).toBe(0)
    expect(selection.type).toBe("None")
    selection.setBaseAndExtent(b, 2, a, 1)
    expect(selection.toString()).toBe("lpha be")
    expect(selection.direction).toBe("backward")
    expect(selection.anchorNode).toBe(b)
    expect(selection.focusNode).toBe(a)
    const range = selection.getRangeAt(0)
    expect(range instanceof AbstractRange).toBe(true)
    expect(selection.getRangeAt(0)).toBe(range)
    selection.addRange(document.createRange())
    expect(selection.getRangeAt(0)).toBe(range)
    expect(() => selection.getRangeAt(1)).toThrow()
    selection.extend(b, 4)
    expect(selection.direction).toBe("forward")
    expect(selection.toString()).toBe("ta")
    expect(selection.getRangeAt(0)).not.toBe(range)
    selection.collapseToEnd()
    expect(selection.type).toBe("Caret")
    selection.empty()
    expect(selection.anchorNode).toBeNull()
    expect(() => selection.collapseToStart()).toThrow()
  })

  test("different documents and detached trees are not selectable", () => {
    const {document, a} = sample()
    const other = createDocument()
    const root = other.createElement("p")
    root.textContent = "foreign"
    other.appendChild(root)
    const foreign = other.createRange()
    foreign.selectNodeContents(root)
    const selection = document.getSelection()
    selection.addRange(foreign)
    expect(selection.rangeCount).toBe(0)
    selection.collapse(a, 1)
    selection.setBaseAndExtent(a, 0, root.firstChild!, 2)
    expect(selection.anchorNode).toBe(a)
    const detached = document.createTextNode("detached")
    selection.collapse(detached, 1)
    expect(selection.anchorNode).toBe(a)
    expect(() => selection.getRangeAt(0).comparePoint(root, 0)).toThrow("different trees")
    expect(selection.getRangeAt(0).isPointInRange(root, 0)).toBe(false)
    const associated = selection.getRangeAt(0)
    associated.setStart(root.firstChild!, 1)
    expect(selection.rangeCount).toBe(0)
    expect(selection.anchorNode).toBeNull()
    expect(selection.focusNode).toBeNull()
    expect(() => selection.getRangeAt(0)).toThrow()
  })

  test("boundary setters normalize ordering, validate offsets and compare ancestor positions", () => {
    const {document, root, first, a, b} = sample()
    const range = document.createRange()
    range.setStart(a, 1)
    range.setEnd(b, 2)
    expect(range.commonAncestorContainer).toBe(root)
    expect(range.comparePoint(a, 0)).toBe(-1)
    expect(range.comparePoint(a, 3)).toBe(0)
    expect(range.comparePoint(b, 3)).toBe(1)
    expect(range.intersectsNode(first)).toBe(true)
    expect(() => range.setEnd(b, -1)).toThrow()
    expect(() => range.setStart(a, a.length + 1)).toThrow()
    const clone = range.cloneRange()
    expect(clone.compareBoundaryPoints(Range.START_TO_START, range)).toBe(0)
    expect(clone.compareBoundaryPoints(Range.END_TO_END, range)).toBe(0)
    expect(clone.compareBoundaryPoints(Range.START_TO_END, range)).toBe(1)
    expect(clone.compareBoundaryPoints(Range.END_TO_START, range)).toBe(-1)
    range.setStart(b, 4)
    expect(range.collapsed).toBe(true)
    range.setEnd(a, 0)
    expect(range.collapsed).toBe(true)
    expect(range.startContainer).toBe(a)
  })

  test("CharacterData insert/delete/replace move live boundaries in UTF-16, snapshots stay fixed", () => {
    const {document, a} = sample()
    a.data = "A😀BCDEF"
    const range = document.createRange()
    range.setStart(a, 3)
    range.setEnd(a, 7)
    const snapshot = new StaticRange({startContainer: a, startOffset: 3, endContainer: a, endOffset: 7})
    a.insertData(1, "xy")
    expect([range.startOffset, range.endOffset]).toEqual([5, 9])
    a.replaceData(4, 3, "q")
    expect([range.startOffset, range.endOffset]).toEqual([4, 7])
    a.deleteData(0, 2)
    expect([range.startOffset, range.endOffset]).toEqual([2, 5])
    expect([snapshot.startOffset, snapshot.endOffset]).toEqual([3, 7])
    expect(a.substringData(0, 2)).toBe("y\ud83d")
    a.data = "short"
    expect([range.startOffset, range.endOffset]).toEqual([0, 0])
  })

  test("splitText relocates live boundaries and parent positions without losing text", () => {
    const {document, first, a} = sample()
    const range = document.createRange()
    range.setStart(a, 1)
    range.setEnd(a, 5)
    const after = document.createRange()
    after.setStart(first, 1)
    const next = a.splitText(3)
    expect(a.data).toBe("alp")
    expect(next.data).toBe("ha ")
    expect(range.startContainer).toBe(a)
    expect(range.endContainer).toBe(next)
    expect(range.endOffset).toBe(2)
    expect(range.toString()).toBe("lpha")
    expect(after.startOffset).toBe(2)
    const detached = document.createTextNode("abcdef")
    range.setStart(detached, 5)
    range.collapse(true)
    detached.splitText(2)
    expect(range.startContainer).toBe(detached)
    expect(range.startOffset).toBe(2)
  })

  test("child insertion/removal adjust parent boundaries; explicit removal relocates descendants", () => {
    const {document, root, first, code, a, c} = sample()
    const range = document.createRange()
    range.setStart(root, 1)
    range.setEnd(root, 3)
    root.insertBefore(document.createElement("hr"), first)
    expect([range.startOffset, range.endOffset]).toEqual([2, 4])
    root.removeChild(code)
    expect([range.startOffset, range.endOffset]).toEqual([2, 3])
    range.setStart(a, 2)
    range.setEnd(c, 3)
    root.removeChild(first)
    expect(range.startContainer).toBe(root)
    expect(range.startOffset).toBe(1)
    expect(range.endContainer).toBe(c)
  })

  test("same-Document connected reparent preserves exact selected text identity", () => {
    const {document, root, first, last, a} = sample()
    const selection = document.getSelection()
    selection.setBaseAndExtent(a, 5, a, 1)
    const range = selection.getRangeAt(0)
    last.appendChild(first)
    expect(selection.getRangeAt(0)).toBe(range)
    expect(selection.anchorNode).toBe(a)
    expect(selection.focusNode).toBe(a)
    expect(selection.toString()).toBe("lpha")
    expect(selection.direction).toBe("backward")
    root.replaceChildren(last)
    expect(selection.anchorNode).toBe(a)
    last.removeChild(first)
    expect(selection.anchorNode).toBe(last)
  })

  test("cross-Document adoption collapses old Document boundaries before moving nodes", () => {
    const {document, first, a} = sample()
    const selection = document.getSelection()
    selection.setBaseAndExtent(a, 1, a, 3)
    const other = createDocument()
    const root = other.createElement("div")
    other.appendChild(root)
    root.appendChild(a)
    expect(a.ownerDocument).toBe(other)
    expect(selection.anchorNode).toBe(first)
    expect(selection.focusNode).toBe(first)
    expect(selection.isCollapsed).toBe(true)
  })

  test("moving one selected endpoint past the other preserves anchor/focus and normalizes range order", () => {
    const {document, root, first, a, b} = sample()
    const selection = document.getSelection()
    selection.setBaseAndExtent(a, 2, b, 3)
    root.appendChild(first)
    expect(selection.anchorNode).toBe(a)
    expect(selection.anchorOffset).toBe(2)
    expect(selection.focusNode).toBe(b)
    expect(selection.focusOffset).toBe(3)
    expect(selection.direction).toBe("backward")
    expect(selection.getRangeAt(0).startContainer).toBe(b)
    expect(selection.getRangeAt(0).endContainer).toBe(a)
  })

  test("selectionchange coalesces transactions and direct live-range changes without DOM mutation", async () => {
    const {document, a, b} = sample()
    let count = 0
    let mutations = 0
    document.addEventListener("selectionchange", () => count += 1)
    document.subscribeMutations(() => mutations += 1)
    document.transaction(() => {
      document.getSelection().collapse(a, 1)
      document.getSelection().extend(b, 2)
      document.getSelection().getRangeAt(0).setEnd(b, 3)
    })
    expect(count).toBe(0)
    await Promise.resolve()
    expect(count).toBe(1)
    expect(mutations).toBe(0)
    a.insertData(0, "!")
    await Promise.resolve()
    expect(count).toBe(2)
    expect(mutations).toBe(1)
  })

  test("Range.toString is raw text, not HTML or visual-block clipboard serialization", () => {
    const {document, root, a, b, c} = sample()
    a.data = "😀 "
    root.insertBefore(document.createComment("not text"), root.lastChild)
    const range = document.createRange()
    range.setStart(a, 0)
    range.setEnd(c, c.length)
    expect(range.toString()).toBe("😀 beta\nγ omega")
    range.setStart(b, 0)
    range.setEnd(b, 4)
    expect(range.toString()).toBe("beta")
  })

  test("deleteContents across blocks preserves outside nodes and collapses at the DOM boundary", () => {
    const {document, root, first, code, last, a, c} = sample()
    const range = document.createRange()
    range.setStart(a, 2)
    range.setEnd(c, 3)
    range.deleteContents()
    expect(a.data).toBe("al")
    expect(c.data).toBe("ega")
    expect(root.childNodes).toEqual([first, last])
    expect(code.parentNode).toBeNull()
    expect(range.collapsed).toBe(true)
    expect(range.startContainer).toBe(root)
    expect(range.startOffset).toBe(1)
  })

  test("clone/extractContents preserve partial ancestry; extraction moves fully selected nodes", () => {
    const {document, first, code, a, c} = sample()
    code.setAttribute("data-test", "keep")
    const range = document.createRange()
    range.setStart(a, 2)
    range.setEnd(c, 3)
    const clone = range.cloneContents()
    expect(clone.textContent).toBe("pha beta\nγ om")
    expect(clone.firstChild?.nodeName).toBe("P")
    expect(clone.querySelector("code")?.getAttribute("data-test")).toBe("keep")
    expect(clone.querySelector("code")).not.toBe(code)
    expect(first.firstChild).toBe(a)
    const extracted = range.extractContents()
    expect(extracted.textContent).toBe(clone.textContent)
    expect(extracted.querySelector("code")).toBe(code)
    expect(range.collapsed).toBe(true)
  })

  test("extractContents retains fully selected Text identity", () => {
    const {document, first, a} = sample()
    const range = document.createRange()
    range.selectNode(a)
    const extracted = range.extractContents()
    expect(extracted.firstChild).toBe(a)
    expect(first.childNodes).toHaveLength(0)
  })

  test("insertNode splits Text and expands a collapsed range around inserted content", () => {
    const {document, first, a} = sample()
    const range = document.createRange()
    range.setStart(a, 2)
    range.collapse(true)
    const inserted = document.createTextNode("X\nY")
    range.insertNode(inserted)
    expect(first.textContent).toBe("alX\nYpha ")
    expect(first.childNodes[1]).toBe(inserted)
    expect(range.toString()).toBe("X\nY")
    range.collapse(false)
    expect(range.startContainer).toBe(first)
    expect(range.startOffset).toBe(2)
  })

  test("surroundContents wraps a complete text selection and rejects partial elements atomically", () => {
    const {document, first, a, b} = sample()
    const range = document.createRange()
    range.setStart(a, 1)
    range.setEnd(a, 4)
    const wrapper = document.createElement("strong")
    range.surroundContents(wrapper)
    expect(wrapper.textContent).toBe("lph")
    expect(first.textContent).toBe("alpha ")
    expect(range.toString()).toBe("lph")
    range.setStart(wrapper.firstChild!, 1)
    range.setEnd(b, 2)
    const original = first.textContent
    expect(() => range.surroundContents(document.createElement("em"))).toThrow("partially")
    expect(first.textContent).toBe(original)
  })

  test("insertNode reparent preserves selection and invalid document insertions fail before detaching", () => {
    const {document, root, first, last, a} = sample()
    const selection = document.getSelection()
    selection.setBaseAndExtent(a, 1, a, 3)
    const range = document.createRange()
    range.selectNodeContents(last)
    range.collapse(false)
    range.insertNode(first)
    expect(selection.anchorNode).toBe(a)
    expect(selection.toString()).toBe("lp")
    range.setStart(document, 1)
    range.collapse(true)
    expect(() => range.insertNode(last)).toThrow()
    expect(last.parentNode).toBe(root)
  })

  test("appending text with a live caret does not materialize every existing sibling", () => {
    const document = createDocument()
    const root = document.createElement("code")
    document.appendChild(root)
    const text = document.createTextNode("start")
    root.appendChild(text)
    document.getSelection().collapse(text, 2)
    let reads = 0
    Object.defineProperty(root, "childNodes", {
      get() {
        reads += 1
        const nodes = []
        for (let node = root.firstChild; node; node = node.nextSibling) nodes.push(node)
        return nodes
      },
    })
    for (let index = 0; index < 1000; index += 1) root.appendChild(document.createTextNode("x"))
    expect(reads).toBe(0)
    expect(document.getSelection().anchorNode).toBe(text)
    expect(document.getSelection().anchorOffset).toBe(2)
  })
})

describe("shared raw-text positions and additional decorations", () => {
  test("mapping spans and UTF-16 positions includes literal LF and excludes comments", () => {
    const {document, root, first, a, b, c} = sample()
    const comment = document.createComment("ignore")
    first.appendChild(comment)
    expect(textOffsetAtPosition(root, b, 2)).toBe(8)
    expect(textOffsetAtPosition(root, first, 1)).toBe(6)
    expect(textOffsetAtPosition(root, comment, 3)).toBe(6)
    expect(textPositionAtOffset(root, 8)).toEqual({node: b, offset: 2})
    expect(textPositionAtOffset(root, 6)).toEqual({node: a, offset: 6})
    expect(textPositionAtOffset(root, 1e9)).toEqual({node: c, offset: c.length})
    expect(textOffsetAtPosition(root, document.createTextNode("other"), 0)).toBeNull()
  })

  test("mapping invalidates synchronously inside mutation transactions and after moves", () => {
    const {document, root, first, last, a, b} = sample()
    expect(textOffsetAtPosition(root, b, 1)).toBe(7)
    document.transaction(() => {
      a.appendData("more")
      expect(textOffsetAtPosition(root, b, 1)).toBe(11)
      last.appendChild(first)
      expect(textOffsetAtPosition(root, b, 1)).toBe(1)
    })
    const detached = document.createElement("p")
    detached.append("a")
    expect(textPositionAtOffset(detached, 1).offset).toBe(1)
    detached.textContent = "long"
    expect(textPositionAtOffset(detached, 4).offset).toBe(4)
  })

  test("mapping reuses its index for style and scroll changes", () => {
    const {root, first, a} = sample()
    textPositionAtOffset(root, 1)
    let childReads = 0
    Object.defineProperty(a, "nodeValue", {get() { childReads += 1; return "alpha " }})
    first.setAttribute("style", "color: red")
    textPositionAtOffset(root, 2)
    textOffsetAtPosition(root, a, 3)
    expect(childReads).toBe(0)
  })

  test("secondary ranges stay separate from Selection, notify live updates and release on cleanup", () => {
    const {document, a, b} = sample()
    const owner = {}
    const selected = document.createRange()
    selected.setStart(a, 1)
    selected.setEnd(a, 3)
    const caret = document.createRange()
    caret.setStart(b, 2)
    caret.collapse(true)
    let updates = 0
    const release = subscribeDocumentTextHighlights(document, () => updates += 1)
    setDocumentTextHighlights(document, owner, [selected, caret], {color: "#123456"})
    expect(document.getSelection().rangeCount).toBe(0)
    expect(readDocumentTextHighlights(document)).toHaveLength(2)
    expect(readDocumentTextHighlights(document)[1]?.range.collapsed).toBe(true)
    selected.setEnd(a, 4)
    expect(updates).toBe(2)
    clearDocumentTextHighlights(document, owner)
    expect(updates).toBe(3)
    expect(readDocumentTextHighlights(document)).toHaveLength(0)
    selected.setEnd(a, 5)
    expect(updates).toBe(3)
    release()
    const foreign = createDocument().createRange()
    expect(() => setDocumentTextHighlights(document, owner, [foreign])).toThrow()
  })
})
