import {expect, spyOn, test} from "bun:test"
import {createCodeEditorModel} from "../code-editor-model.ts"

test("normalization merges overlap and duplicate carets, preserving primary direction", () => {
  const model = createCodeEditorModel({value: "0123456789", selections: [
    {anchor: 7, head: 7}, {anchor: 6, head: 3}, {anchor: 1, head: 4}, {anchor: 7, head: 7},
  ], primary: 1})
  expect(model.snapshot.selections).toEqual([{anchor: 6, head: 1}, {anchor: 7, head: 7}])
  expect(model.snapshot.primary).toBe(0)
  model.addSelection({anchor: 9, head: 8})
  expect(model.snapshot.primary).toBe(2)
  model.addSelection({anchor: 9, head: 9})
  expect(model.snapshot.selections).toEqual([{anchor: 6, head: 1}, {anchor: 7, head: 7}, {anchor: 8, head: 9}])
  expect(model.snapshot.primary).toBe(2)
  expect(model.selectedText()).toBe("12345\n8")
})

test("one transaction replaces every range against original offsets and history restores directions", () => {
  const ranges = [{anchor: 2, head: 1}, {anchor: 4, head: 5}]
  const model = createCodeEditorModel({value: "abcdef", selections: ranges, primary: 1})
  const before = model.snapshot
  expect(model.insertText("XYZ")).toBe(true)
  expect(model.snapshot.value).toBe("aXYZcdXYZf")
  expect(model.snapshot.selections).toEqual([{anchor: 4, head: 4}, {anchor: 9, head: 9}])
  expect(model.snapshot.primary).toBe(1)
  expect(model.snapshot.revision).toBe(1)
  expect(before.value).toBe("abcdef")
  expect(before.selections).toEqual(ranges)
  expect(model.undo()).toBe(true)
  expect(model.snapshot.value).toBe("abcdef")
  expect(model.snapshot.selections).toEqual(ranges)
  expect(model.snapshot.primary).toBe(1)
  expect(model.snapshot.revision).toBe(2)
  expect(model.redo()).toBe(true)
  expect(model.snapshot.value).toBe("aXYZcdXYZf")
  expect(model.snapshot.revision).toBe(3)
})

test("overlapping deletion expansions deduplicate edits and resulting carets", () => {
  const model = createCodeEditorModel({value: "hello world", selections: [{anchor: 2, head: 2}, {anchor: 4, head: 4}], primary: 1})
  model.deleteBackward("word")
  expect(model.snapshot.value).toBe("o world")
  expect(model.snapshot.selections).toEqual([{anchor: 0, head: 0}])
  model.undo()
  expect(model.snapshot.selections).toEqual([{anchor: 2, head: 2}, {anchor: 4, head: 4}])
  expect(model.snapshot.primary).toBe(1)
})

test("paste distributes equal-count lines in source order and otherwise duplicates full payload", () => {
  const model = createCodeEditorModel({value: "a\nb", selections: [{anchor: 0, head: 1}, {anchor: 2, head: 3}], primary: 1})
  model.paste("first\r\nsecond")
  expect(model.snapshot.value).toBe("first\nsecond")
  expect(model.snapshot.selections).toEqual([{anchor: 5, head: 5}, {anchor: 12, head: 12}])
  model.undo()
  model.paste(["x", "y", "z"])
  expect(model.snapshot.value).toBe("x\ny\nz\nx\ny\nz")
  model.undo()
  model.paste("x\r\ny\r\nz")
  expect(model.snapshot.value).toBe("x\r\ny\r\nz\nx\r\ny\r\nz")
})

test("grapheme movement and deletion keep combining marks, surrogate pairs and ZWJ sequences whole", () => {
  const family = "👨‍👩‍👧‍👦"
  const value = `a\u0301${family}🇺🇦z`
  const model = createCodeEditorModel({value})
  model.move("forward")
  expect(model.snapshot.selections[0]?.head).toBe(2)
  model.move("forward", {extend: true})
  expect(model.selectedText()).toBe(family)
  model.deleteForward()
  expect(model.snapshot.value).toBe("a\u0301🇺🇦z")
  model.undo()
  model.setSelections([{anchor: 3, head: 3}])
  model.deleteBackward()
  expect(model.snapshot.value).toBe("a\u0301🇺🇦z")
  model.undo()
  model.setSelections([{anchor: 3, head: 3}])
  model.deleteForward()
  expect(model.snapshot.value).toBe("a\u0301🇺🇦z")
})

test("word, line and document movement preserve directional extension and collapse selected ranges", () => {
  const model = createCodeEditorModel({value: "Привет, мир!\r\nsecond line"})
  model.move("forward", {unit: "word"})
  expect(model.snapshot.selections[0]?.head).toBe(6)
  model.move("forward", {unit: "line", extend: true})
  expect(model.selectedText()).toBe(", мир!")
  model.move("backward")
  expect(model.snapshot.selections).toEqual([{anchor: 6, head: 6}])
  model.move("forward", {unit: "document", extend: true})
  expect(model.snapshot.selections).toEqual([{anchor: 6, head: 25}])
  model.move("backward", {unit: "line", extend: true})
  expect(model.snapshot.selections).toEqual([{anchor: 6, head: 14}])
})

test("read-only rejects editing and history but keeps selection and copy available", () => {
  const model = createCodeEditorModel({value: "abc", readOnly: true, selections: [{anchor: 0, head: 2}]})
  const before = model.snapshot
  expect(model.insertText("x")).toBe(false)
  expect(model.paste("x")).toBe(false)
  expect(model.deleteForward()).toBe(false)
  expect(model.deleteBackward()).toBe(false)
  expect(model.beginComposition()).toBe(false)
  expect(model.undo()).toBe(false)
  expect(model.redo()).toBe(false)
  expect(model.snapshot).toBe(before)
  expect(model.selectedText()).toBe("ab")
  expect(model.move("forward")).toBe(true)
  expect(model.snapshot.selections).toEqual([{anchor: 2, head: 2}])
  model.setReadOnly(false)
  model.insertText("x")
  model.setReadOnly(true)
  expect(model.undo()).toBe(false)
  model.setReadOnly(false)
  expect(model.undo()).toBe(true)
  expect(model.snapshot.value).toBe("abc")
})

test("composition previews all ranges from base and commits as one undo transaction", () => {
  const selections = [{anchor: 0, head: 1}, {anchor: 3, head: 2}]
  const model = createCodeEditorModel({value: "a b", selections, primary: 1})
  model.beginComposition()
  expect(model.snapshot.composing).toBe(true)
  model.updateComposition("に")
  expect(model.snapshot.value).toBe("に に")
  model.updateComposition("日本")
  expect(model.snapshot.value).toBe("日本 日本")
  expect(model.snapshot.canUndo).toBe(false)
  expect(model.insertText("wrong")).toBe(false)
  expect(model.setSelections([{anchor: 0, head: 0}])).toBe(false)
  expect(model.beginComposition()).toBe(false)
  model.commitComposition("日本語")
  expect(model.snapshot.value).toBe("日本語 日本語")
  expect(model.snapshot.selections).toEqual([{anchor: 3, head: 3}, {anchor: 7, head: 7}])
  expect(model.snapshot.composing).toBe(false)
  model.undo()
  expect(model.snapshot.value).toBe("a b")
  expect(model.snapshot.selections).toEqual(selections)
  expect(model.snapshot.primary).toBe(1)
  expect(model.undo()).toBe(false)
  model.redo()
  expect(model.snapshot.value).toBe("日本語 日本語")
})

test("composition cancellation and invalid updates preserve base and redo", () => {
  const model = createCodeEditorModel({value: "abc", selections: [{anchor: 1, head: 2}]})
  model.insertText("x")
  model.undo()
  model.beginComposition()
  model.updateComposition("preview")
  const preview = model.snapshot
  expect(() => model.updateComposition(null as unknown as string)).toThrow(TypeError)
  expect(model.snapshot).toBe(preview)
  expect(() => model.commitComposition(null as unknown as string)).toThrow(TypeError)
  expect(model.snapshot).toBe(preview)
  model.cancelComposition()
  expect(model.snapshot.value).toBe("abc")
  expect(model.snapshot.selections).toEqual([{anchor: 1, head: 2}])
  expect(model.snapshot.canRedo).toBe(true)
  model.redo()
  expect(model.snapshot.value).toBe("axc")
  model.beginComposition()
  model.updateComposition("new")
  model.setReadOnly(true)
  expect(model.snapshot.value).toBe("axc")
  expect(model.snapshot.composing).toBe(false)
})

test("external replacement explicitly maps selections or resets and clears old history", () => {
  const model = createCodeEditorModel({value: "abcd", selections: [{anchor: 1, head: 1}, {anchor: 4, head: 3}], primary: 1})
  model.replaceValue("aXXbcd", {selection: "map"})
  expect(model.snapshot.selections).toEqual([{anchor: 3, head: 3}, {anchor: 6, head: 5}])
  expect(model.snapshot.primary).toBe(1)
  model.insertText("x")
  model.beginComposition()
  model.updateComposition("temp")
  model.replaceValue("external", {selection: "reset"})
  expect(model.snapshot.value).toBe("external")
  expect(model.snapshot.selections).toEqual([{anchor: 0, head: 0}])
  expect(model.snapshot.primary).toBe(0)
  expect(model.snapshot.composing).toBe(false)
  expect(model.snapshot.canUndo).toBe(false)
  expect(model.snapshot.canRedo).toBe(false)
})

test("snapshots are immutable, listeners release, validation is atomic and history is bounded", () => {
  const model = createCodeEditorModel({value: "", historyLimit: 1})
  const snapshots: typeof model.snapshot[] = []
  const unsubscribe = model.subscribe(snapshot => snapshots.push(snapshot))
  expect(Object.isFrozen(model.snapshot)).toBe(true)
  expect(Object.isFrozen(model.snapshot.selections)).toBe(true)
  expect(Object.isFrozen(model.snapshot.selections[0])).toBe(true)
  model.insertText("a")
  model.insertText("b")
  expect(snapshots).toHaveLength(2)
  expect(snapshots[0]?.value).toBe("a")
  const before = model.snapshot
  expect(() => model.setSelections([{anchor: Number.NaN, head: 0}])).toThrow(RangeError)
  expect(() => model.setSelections([{anchor: 0, head: 0}], 1)).toThrow(RangeError)
  expect(model.snapshot).toBe(before)
  unsubscribe()
  model.undo()
  expect(model.snapshot.value).toBe("a")
  expect(model.undo()).toBe(false)
  expect(snapshots).toHaveLength(2)
  model.insertText("x")
  expect(model.snapshot.canRedo).toBe(false)
})

test("empty and boundary commands remain no-ops and adjacent nonempty ranges stay independent", () => {
  const empty = createCodeEditorModel({value: ""})
  expect(empty.deleteBackward()).toBe(false)
  expect(empty.deleteForward()).toBe(false)
  expect(empty.move("backward")).toBe(false)
  expect(empty.move("forward")).toBe(false)
  expect(empty.insertText("")).toBe(false)
  const model = createCodeEditorModel({value: "abcd", selections: [{anchor: 0, head: 2}, {anchor: 2, head: 4}], primary: 1})
  expect(model.snapshot.selections).toHaveLength(2)
  model.paste(["left", "right"])
  expect(model.snapshot.value).toBe("leftright")
  expect(model.snapshot.selections).toEqual([{anchor: 4, head: 4}, {anchor: 9, head: 9}])
})

test("logical vertical movement keeps desired columns across short lines and treats CRLF as one grapheme", () => {
  const model = createCodeEditorModel({value: "first\r\nx\r\nthird", selections: [{anchor: 4, head: 4}]})
  model.moveVertical("down")
  expect(model.snapshot.selections).toEqual([{anchor: 8, head: 8}])
  model.moveVertical("down")
  expect(model.snapshot.selections).toEqual([{anchor: 14, head: 14}])
  model.moveVertical("up", {extend: true})
  expect(model.snapshot.selections).toEqual([{anchor: 14, head: 8}])
  model.setSelections([{anchor: 7, head: 7}])
  model.deleteBackward()
  expect(model.snapshot.value).toBe("firstx\r\nthird")
  const emptyFirst = createCodeEditorModel({value: "\nnext"})
  expect(emptyFirst.move("backward", {unit: "line"})).toBe(false)
})

test("grapheme movement segments only the touched line and reuses its cache", () => {
  const value = "unchanged\n".repeat(100_000) + "tail"
  const model = createCodeEditorModel({value, selections: [{anchor: value.length, head: value.length}]})
  const original = Intl.Segmenter.prototype.segment
  const lengths: number[] = []
  const spy = spyOn(Intl.Segmenter.prototype, "segment").mockImplementation(function (this: Intl.Segmenter, value: string) {
    lengths.push(value.length)
    return original.call(this, value)
  })
  try {
    model.move("backward")
    model.move("backward")
    model.move("forward")
    expect(lengths).toEqual([4])
  } finally { spy.mockRestore() }
})

test("logical navigation and deletion preserve standalone CR line endings", () => {
  const model = createCodeEditorModel({value: "ab\r\rcde", selections: [{anchor: 1, head: 1}]})
  model.moveVertical("down")
  expect(model.snapshot.selections[0]?.head).toBe(3)
  model.moveVertical("down")
  expect(model.snapshot.selections[0]?.head).toBe(5)
  model.move("backward", {unit: "line"})
  expect(model.snapshot.selections[0]?.head).toBe(4)
  model.deleteBackward()
  expect(model.snapshot.value).toBe("ab\rcde")
})
