import {defineReportStory} from "./story-types.ts"

export const story_algorithms_fixed_baseline = defineReportStory("algorithms/fixed/baseline")
export const story_algorithms_fixed_down = defineReportStory("algorithms/fixed/down")
export const story_algorithms_fixed_compound = defineReportStory("algorithms/fixed/compound")
export const story_algorithms_fixed_invalid = defineReportStory("algorithms/fixed/invalid")
export const story_algorithms_adaptive_shared = defineReportStory("algorithms/adaptive/shared")
export const story_algorithms_adaptive_down = defineReportStory("algorithms/adaptive/down")
export const story_algorithms_adaptive_compound = defineReportStory("algorithms/adaptive/compound")
export const story_algorithms_adaptive_diagnostics = defineReportStory("algorithms/adaptive/diagnostics")
export const story_algorithms_adaptive_no_assignment = defineReportStory("algorithms/adaptive/no-assignment")
export const story_algorithms_top_down_baseline = defineReportStory("algorithms/top-down/baseline")
export const story_algorithms_top_down_cycle = defineReportStory("algorithms/top-down/cycle")
export const story_algorithms_coffman_graham_baseline = defineReportStory("algorithms/coffman-graham/baseline")
export const story_algorithms_coffman_graham_narrow = defineReportStory("algorithms/coffman-graham/narrow")
export const story_algorithms_coffman_graham_cycle = defineReportStory("algorithms/coffman-graham/cycle")
export const story_protocol_graph_compound = defineReportStory("protocol/graph/compound")
export const story_protocol_result_geometry = defineReportStory("protocol/result/geometry")
export const story_workers_fixed_equivalence = defineReportStory("workers/fixed/equivalence")
export const story_workers_fixed_failure = defineReportStory("workers/fixed/failure")
export const story_workers_adaptive_equivalence = defineReportStory("workers/adaptive/equivalence")
export const story_workers_adaptive_failure = defineReportStory("workers/adaptive/failure")
export const story_workers_top_down_equivalence = defineReportStory("workers/top-down/equivalence")
export const story_workers_top_down_failure = defineReportStory("workers/top-down/failure")
export const story_workers_coffman_graham_equivalence = defineReportStory("workers/coffman-graham/equivalence")
export const story_workers_coffman_graham_failure = defineReportStory("workers/coffman-graham/failure")
export const story_workers_transport_lifecycle = defineReportStory("workers/transport/lifecycle")
export const story_workers_transport_faults = defineReportStory("workers/transport/faults")
